---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
   - name: import varivale
     include_vars: varivale/vpc_setup

   - name: careat vpofile vpc
     ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      dns_support: yes
      dns_hostname: yes
      tenancy: default
      state: present
     register: vpcout