- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
   - name: import varivale
     include_vars: variable/vpc_setup

   - name: careat vpofile vpc
     ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
     register: vpcout

   #- debug:
    #  var: vpcout
   # create public subnet 1
   - name: create public subnet 1
     ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        state: "{{state}}"
        map_public: yes
        tags:
             Name: PubSub_1
     register: PubSub1Cidr_out
    
    # create public subnet 2
   - name: create public subnet 2
     ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{PubSub2Cidr}}"
        state: "{{state}}"
        map_public: yes
        tags:
             Name: PubSub_2
     register: PubSub2Cidr_out
    
    # create public subnet 3
   - name: create public subnet 3
     ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{PubSub3Cidr}}"
        state: "{{state}}"
        map_public: yes
        tags:
             Name: PubSub_3
     register: PubSub3Cidr_out

     # create private subnet 1
   - name: create private subnet 1
     ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        cidr: "{{PrivSub1Cidr}}"
        state: "{{state}}"
        tags:
             Name: privSub_1
     register: PrivSub1Cidr_out

          # create private subnet 2
   - name: create private subnet 2
     ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        cidr: "{{PrivSub2Cidr}}"
        state: "{{state}}"
        tags:
             Name: privSub_2
     register: PrivSub2Cidr_out

          # create private subnet 3
   - name: create private subnet 3
     ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        cidr: "{{PrivSub3Cidr}}"
        state: "{{state}}"
        tags:
             Name: privSub_3
     register: PrivSub3Cidr_out

     # Internet Gateway for Public subnets

   - name: Internet Gateway
     ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
             Name: IGW_forPub
     register: IGW_out


          