---
- name: vpro instance setup
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

      - name: import vpc out variable
        include_vars: variable/vpc_out_variable

      - name: impor vpro stack variable
        include_vars: variable/vpro_stack

      - name: create key painr
        ec2_key:
            name: vp_stack_key
            region: "{{region}}"
        register: vp_stack_key_out


      - name: copy the vp_stack_key
        copy:
            content: "{{vp_stack_key_out.key.private_key}}"
            dest: "./vp_stack_key.pem"
            mode: 0600
        when: vp_stack_key_out.changed

      - name: create sg for fro load banced
        ec2_group:
            name: vporELB_Sg
            description: SG for the ELB
            region: "{{region}}"
            vpc_id: "{{vpcid}}"
            purge_rules: no
            rules:
                - proto: tcp
                  from_port: 80
                  to_port: 80
                  cidr_ip: 0.0.0.0/0
        register: vporELB_Sg_out


      - name: create sg for vpro stack
        ec2_group:
            name: vpor_stack_sg
            description: SG for the vpor stack
            region: "{{region}}"
            vpc_id: "{{vpcid}}"
            purge_rules: no
            rules:
                - proto: tcp
                  from_port: 80
                  to_port: 80
                  group_id: "{{vporELB_Sg_out.group_id}}"

                - proto: tcp
                  from_port: 22
                  to_port: 22
                  group_id: "{{bastion_sg}}"
        register: vpor_stack_sg_out


      - name: update the vpor_stack_sg
        ec2_group:
            name: vpor_stack_sg
            description: SG for the vpor stack
            region: "{{region}}"
            vpc_id: "{{vpcid}}"
            purge_rules: no
            rules:
                - proto: all
                  group_id: "{{vpor_stack_sg_out.group_id}}"

      - name: createing Nginx server web01
        ec2:
            key_name: vp_stack_key
            region: "{{region}}"
            instance_type: t2.micro
            image: "{{nginx_ami}}"
            wait: yes
            wait_timeout: 300
            instance_tags:
                Name: Nginx_Server
            exact_count: 1
            count_tag:
                Name: Nginx_Server
            group_id: "{{vpor_stack_sg_out.group_id}}"
            vpc_subnet_id: "{{privsub1id}}"
        register: web01_out

             



